/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',

        'grey-primary': 'var(--color-grey-primary)',
        'grey-hover': 'var(--color-grey-hover)',
        'grey-secondary': 'var(--color-grey-secondary)',
        'grey-placeholder': 'var(--color-grey-placeholder)',
        'grey-disabled': 'var(--color-grey-disabled)',
        'grey-border': 'var(--color-grey-border)',
        'grey-background': 'var(--color-grey-background)',
        'grey-background-light': 'var(--color-grey-background-light)',
        'grey-white': 'var(--color-grey-white)',

        'purple-primary': 'var(--color-purple-primary)',
        'purple-hover': 'var(--color-purple-hover)',
        'purple-secondary': 'var(--color-purple-secondary)',
        'purple-placeholder': 'var(--color-purple-placeholder)',
        'purple-disabled': 'var(--color-purple-disabled)',
        'purple-border': 'var(--color-purple-border)',
        'purple-border-light': 'var(--color-purple-border-light)',
        'purple-background': 'var(--color-purple-background)',
        'purple-background-light': 'var(--color-purple-background-light)',

        'red-primary': 'var(--color-red-primary)',
        'red-hover': 'var(--color-red-hover)',
        'red-secondary': 'var(--color-red-secondary)',
        'red-placeholder': 'var(--color-red-placeholder)',
        'red-disabled': 'var(--color-red-disabled)',
        'red-border': 'var(--color-red-border)',
        'red-background': 'var(--color-red-background)',
        'red-background-light': 'var(--color-red-background-light)',

        'green-primary': 'var(--color-green-primary)',
        'green-hover': 'var(--color-green-hover)',
        'green-secondary': 'var(--color-green-secondary)',
        'green-placeholder': 'var(--color-green-placeholder)',
        'green-disabled': 'var(--color-green-disabled)',
        'green-border': 'var(--color-green-border)',
        'green-background': 'var(--color-green-background)',
        'green-background-light': 'var(--color-green-background-light)',

        'yellow-primary': 'var(--color-yellow-primary)',
        'yellow-hover': 'var(--color-yellow-hover)',
        'yellow-secondary': 'var(--color-yellow-secondary)',
        'yellow-placeholder': 'var(--color-yellow-placeholder)',
        'yellow-disabled': 'var(--color-yellow-disabled)',
        'yellow-border': 'var(--color-yellow-border)',
        'yellow-background': 'var(--color-yellow-background)',
        'yellow-background-light': 'var(--color-yellow-background-light)',

        'orange-primary': 'var(--color-orange-primary)',
        'orange-hover': 'var(--color-orange-hover)',
        'orange-secondary': 'var(--color-orange-secondary)',
        'orange-placeholder': 'var(--color-orange-placeholder)',
        'orange-disabled': 'var(--color-orange-disabled)',
        'orange-border': 'var(--color-orange-border)',
        'orange-background': 'var(--color-orange-background)',
        'orange-background-light': 'var(--color-orange-background-light)',

        'blue-58': 'var(--color-blue-58)',
        'blue-96': 'var(--color-blue-96)',

        'surface-page': 'var(--color-surface-page)',
        'surface-card': 'var(--color-surface-card)',
        'surface-sidebar': 'var(--color-surface-sidebar)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'surface-popover': 'var(--color-surface-popover)',
        'surface-row': 'var(--color-surface-row)',
        'surface-row-hover': 'var(--color-surface-row-hover)',
      },
      spacing: {
        '2xs': '0.125rem',
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        '2xl': '2.5rem',
        '3xl': '3rem',
        '4xl': '5rem',
        '58.5': '14.625rem',
      },
      borderRadius: {
        xs: '0.125rem',
      },
      fontSize: {
        '2xl': ['28px', '32px'],
        l: ['20px', '30px'],
        m: ['16px', '24px'],
        s: ['14px', '21px'],
        r: ['13px', '20px'],
        xs: ['12px', '18px'],
        '2xs': ['10px', '12px'],
        h1: ['1.25rem', '140%'],
        h2: ['1rem', '140%'],
        default: ['0.875rem', '140%'],
        small: ['0.75rem', '140%'],
        tiny: ['0.625rem', '140%'],
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        'sticky-bottom': '0 -8px 24px rgba(8, 5, 37, 0.06)',
        'sticky-top': '0 8px 24px rgba(8, 5, 37, 0.06)',
        'sticky-left': '8px 0 12px rgba(8, 5, 37, 0.06)',
        glow: '0 0 0 1px rgba(255,255,255,0.06), 0 20px 80px rgba(0,0,0,0.45)',
      },
      animation: {
        'slide-down': 'slideDown 200ms cubic-bezier(0.87, 0, 0.13, 1)',
        'slide-up': 'slideUp 200ms cubic-bezier(0.87, 0, 0.13, 1)',
        'overlay-show': 'overlayShow 200ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-left-fade-in': 'slideLeftAndFadeIn 200ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-right-fade-in': 'slideRightAndFadeIn 200ms cubic-bezier(0.16, 1, 0.3, 1)',
        'ping-slow': 'ping-slow 5s ease infinite',
        'slide-up-fade': 'slideUpAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        slideDown: {
          from: { height: '0' },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        slideUp: {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: '0' },
        },
        overlayShow: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideLeftAndFadeIn: {
          from: { opacity: '0', transform: 'translate(-100%, 0)' },
          to: { opacity: '1', transform: 'translate(0, 0)' },
        },
        slideRightAndFadeIn: {
          from: { opacity: '0', transform: 'translate(100%, 0)' },
          to: { opacity: '1', transform: 'translate(0, 0)' },
        },
        'ping-slow': {
          '10%': { transform: 'scale(2)', opacity: '0' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        slideUpAndFade: {
          from: { opacity: '0', transform: 'translateY(2px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
